version: '2'
services:
  shiny:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny:${GIT_BRANCH_TAG}
  shiny_proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny-proxy:${GIT_BRANCH_TAG}
    volumes:
      - ./public_key.pem:/public_key.pem
  proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny-reverse-proxy:${GIT_BRANCH_TAG}
    ports:
      - "80:80"
