version: '2'
services:
  shiny:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny:i1388
  shiny_proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny-proxy:i1388
    volumes:
      - ./public_key.pem:/public_key.pem
  proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-shiny-reverse-proxy:i1388
    ports:
      - "80:80"
